### ISSUE TITLE
No detecting signal if using device 0 = Samsung S5H1411 QAM/8VSB Frontend

### ISSUE THREAD

**Issue by jcabrerazuniga** [wirbel-at-vdr-portal/w_scan_cpp-binaries#1]
I have a Pinnacle 801e ( Samsung S5H1411 chip) on Mint 20.3. For the next command:

       w_scan_cpp -fa -c US -A1 -x > initial.scan

the file initial.scan only shows:

#------------------------------------------------------------------------------
# file automatically generated by w_scan_cpp
# https://gen2vdr.de/wirbel
#------------------------------------------------------------------------------
# location and provider: 
# date (yyyy-mm-dd)    : 2022-03-04
# provided by (opt)    : --wirbel--

Any ideas? I installed w-scan-cpp_20210218-1_amd64.deb

Also, I am able to watch TV on Windows using the same machine and the same USB PinnacleTV

Here it is the output I got:

 w_scan_cpp -fa -c US -A1 -x > initial.scan
/*******************************************************************************
 * w_scan_cpp Version 20210218
 ******************************************************************************/

/*******************************************************************************
 * devices
 ******************************************************************************/
Device0 dvb:a0f0: Samsung S5H1411 QAM/8VSB Frontend
/*******************************************************************************
 * Scan Type
 ******************************************************************************/
  ATSC
  country = UNITED STATES
05:48:58 wirbelscan version 2021.03.07 @ VDR 2.5.1
05:48:58 using settings for UNITED STATES
05:48:58 ATSC
05:48:58 VSB US/CA, DVB-T TW
05:48:58 testing '???:474:I0M256:A:6900:0:0:0:0:8192:0:0:0'
05:48:58 device 0 = Samsung S5H1411 QAM/8VSB Frontend
05:48:58 good :-)
05:48:58 frontend Samsung S5H1411 QAM/8VSB Frontend
05:48:58 ATSC     57.00 MHz M10
05:49:02 ATSC     63.00 MHz M10
05:49:06 ATSC     69.00 MHz M10
05:49:10 ATSC     79.00 MHz M10
05:49:14 ATSC     85.00 MHz M10
05:49:18 ATSC    177.00 MHz M10
05:49:22 ATSC    183.00 MHz M10
05:49:26 ATSC    189.00 MHz M10
05:49:30 ATSC    195.00 MHz M10
05:49:34 ATSC    201.00 MHz M10
05:49:38 ATSC    207.00 MHz M10
05:49:42 ATSC    213.00 MHz M10
05:49:46 ATSC    473.00 MHz M10
05:49:50 ATSC    479.00 MHz M10
05:49:54 ATSC    485.00 MHz M10
05:49:58 ATSC    491.00 MHz M10
05:50:02 ATSC    497.00 MHz M10
05:50:06 ATSC    503.00 MHz M10
05:50:10 ATSC    509.00 MHz M10
05:50:14 ATSC    515.00 MHz M10
05:50:18 ATSC    521.00 MHz M10
05:50:22 ATSC    527.00 MHz M10
05:50:26 ATSC    533.00 MHz M10
05:50:30 ATSC    539.00 MHz M10
05:50:34 ATSC    545.00 MHz M10
05:50:38 ATSC    551.00 MHz M10
05:50:42 ATSC    557.00 MHz M10
05:50:46 ATSC    563.00 MHz M10
05:50:50 ATSC    569.00 MHz M10
05:50:54 ATSC    575.00 MHz M10
05:50:58 ATSC    581.00 MHz M10
05:51:02 ATSC    587.00 MHz M10
05:51:06 ATSC    593.00 MHz M10
05:51:10 ATSC    599.00 MHz M10
05:51:14 ATSC    605.00 MHz M10
05:51:18 ATSC    611.00 MHz M10
05:51:22 ATSC    617.00 MHz M10
05:51:26 ATSC    623.00 MHz M10
05:51:30 ATSC    629.00 MHz M10
05:51:34 ATSC    635.00 MHz M10
05:51:38 ATSC    641.00 MHz M10
05:51:42 ATSC    647.00 MHz M10
05:51:46 ATSC    653.00 MHz M10
05:51:50 ATSC    659.00 MHz M10
05:51:54 ATSC    665.00 MHz M10
05:51:58 ATSC    671.00 MHz M10
05:52:02 ATSC    677.00 MHz M10
05:52:06 ATSC    683.00 MHz M10
05:52:10 ATSC    689.00 MHz M10
05:52:14 ATSC    695.00 MHz M10
05:52:18 ATSC    701.00 MHz M10
05:52:22 ATSC    707.00 MHz M10
05:52:26 ATSC    713.00 MHz M10
05:52:30 ATSC    719.00 MHz M10
05:52:34 ATSC    725.00 MHz M10
05:52:38 ATSC    731.00 MHz M10
05:52:42 ATSC    737.00 MHz M10
05:52:46 ATSC    743.00 MHz M10
05:52:50 ATSC    749.00 MHz M10
05:52:54 ATSC    755.00 MHz M10
05:52:58 ATSC    761.00 MHz M10
05:53:02 ATSC    767.00 MHz M10
05:53:06 ATSC    773.00 MHz M10
05:53:10 ATSC    779.00 MHz M10
05:53:14 ATSC    785.00 MHz M10
05:53:18 ATSC    791.00 MHz M10
05:53:22 ATSC    797.00 MHz M10
05:53:26 ATSC    803.00 MHz M10
05:53:30 leaving scanner

**Comment by wirbel-at-vdr-portal** [comment]
So far, i don't see anything related to w_scan_cpp here.

Also, using a device on Windows doesnt tell that it should run on Linux and vice versa. Different kernel driver or firmware gives you complete different experience for the same setup.

No hit at all, may be a hint on missing firmware or use of wrong frequencies.
You could do the usual approach

- check dmesg output for messages from kernel drivers (errors, missing files or modules)
- check firmware for device: it's version reported from driver, it's md5sum and search on linuxtv.org or net for your device for working combinations of fw and driver.
- try different programs, ie. dvbv5-scan together with https://git.linuxtv.org/dtv-scan-tables.git/tree/atsc/us-ATSC-center-frequencies-8VSB

**Comment by wirbel-at-vdr-portal** [comment]
It looks to me, as you're now no longer searching for a solution.

As your issue anyhow doesn't relate to the topic of **building or distributing a binary**,
i'm closing this this bug now.

If you're still searching for help, please use the email address provided. Don't hesitate to write an email.
